// Mock users for comments
export const mockUsers = [
  {
    id: 'mock1',
    username: 'alice',
    name: 'Alice Johnson',
    avatar: '👩‍💻',
  },
  {
    id: 'mock2',
    username: 'bob',
    name: 'Bob Smith',
    avatar: '👨‍🎨',
  },
  {
    id: 'mock3',
    username: 'carol',
    name: 'Carol Lee',
    avatar: '👩‍🚀',
  },
  {
    id: 'mock4',
    username: 'dave',
    name: 'Dave Kim',
    avatar: '👨‍🎓',
  },
  {
    id: 'mock5',
    username: 'eve',
    name: 'Eve Martinez',
    avatar: '👩‍🎨',
  },
];

export const mockCommentTexts = [
  'Great post! Thanks for sharing.',
  'I totally agree with your point.',
  'Interesting perspective!',
  'Can you share more details?',
  'This made my day!',
  'I had a similar experience.',
  'Well said!',
  'Looking forward to more posts like this.',
  'Thanks for the info!',
  'Awesome!',
];

export const mockPosts = [
  {
    id: 'mockpost1',
    userId: 'mock1',
    username: 'alice',
    userAvatar: '👩‍💻',
    text: 'Just finished a great coding session! Check out this cool resource.',
    url: 'https://react.dev/',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    image: undefined,
    comments: [],
  },
  {
    id: 'mockpost2',
    userId: 'mock2',
    username: 'bob',
    userAvatar: '👨‍🎨',
    text: 'Here is a photo from my latest art project.',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    url: undefined,
    comments: [],
  },
  {
    id: 'mockpost3',
    userId: 'mock3',
    username: 'carol',
    userAvatar: '👩‍🚀',
    text: 'Space news: Perseverance rover just sent new images from Mars!',
    url: 'https://mars.nasa.gov/news/',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    image: undefined,
    comments: [],
  },
  {
    id: 'mockpost4',
    userId: 'mock4',
    username: 'dave',
    userAvatar: '👨‍🎓',
    text: 'Studying for finals with this playlist!',
    url: 'https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    image: undefined,
    comments: [],
  },
  {
    id: 'mockpost5',
    userId: 'mock5',
    username: 'eve',
    userAvatar: '👩‍🎨',
    text: 'Check out this amazing sunset I captured yesterday!',
    image: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    url: undefined,
    comments: [],
  },
]; 